import React from "react";
import {
  AirVent,
  Camera,
  Droplets,
  Hammer,
  Laptop,
  Paintbrush,
  ShieldAlert,
  Smartphone,
  WashingMachine,
  Wrench,
  Zap,
} from "lucide-react";

export const SERVICE_CATEGORIES = [
  {
    id: "Linea blanca",
    name: "Linea blanca",
    shortName: "Linea blanca",
    description: "Lavadoras, refrigeradores y electrodomesticos grandes.",
    icon: <WashingMachine className="w-6 h-6" />,
    color: "text-cyan-600",
    bg: "bg-cyan-50 border-cyan-200",
    chip: "bg-cyan-100 text-cyan-700",
    basePrice: 40000,
  },
  {
    id: "Hardware",
    name: "Mantenimiento y reparacion de hardware",
    shortName: "Hardware",
    description: "Laptops, PCs y tablets.",
    icon: <Laptop className="w-6 h-6" />,
    color: "text-indigo-600",
    bg: "bg-indigo-50 border-indigo-200",
    chip: "bg-indigo-100 text-indigo-700",
    basePrice: 40000,
  },
  {
    id: "Moviles",
    name: "Reparacion de dispositivos moviles",
    shortName: "Moviles",
    description: "Pantallas, baterias y diagnostico rapido.",
    icon: <Smartphone className="w-6 h-6" />,
    color: "text-rose-600",
    bg: "bg-rose-50 border-rose-200",
    chip: "bg-rose-100 text-rose-700",
    basePrice: 30000,
  },
  {
    id: "Soporte tecnico y ciberseguridad",
    name: "Soporte tecnico y ciberseguridad",
    shortName: "Soporte TI",
    description: "Malware, recuperacion de datos y seguridad basica.",
    icon: <ShieldAlert className="w-6 h-6" />,
    color: "text-red-600",
    bg: "bg-red-50 border-red-200",
    chip: "bg-red-100 text-red-700",
    basePrice: 40000,
  },
  {
    id: "Domotica y seguridad",
    name: "Domotica y seguridad",
    shortName: "Domotica",
    description: "Camaras IP, cerraduras inteligentes y sensores.",
    icon: <Camera className="w-6 h-6" />,
    color: "text-emerald-600",
    bg: "bg-emerald-50 border-emerald-200",
    chip: "bg-emerald-100 text-emerald-700",
    basePrice: 35000,
  },
  {
    id: "Climatizacion",
    name: "Climatizacion",
    shortName: "Climatizacion",
    description: "Mantenimiento de aires acondicionados.",
    icon: <AirVent className="w-6 h-6" />,
    color: "text-sky-600",
    bg: "bg-sky-50 border-sky-200",
    chip: "bg-sky-100 text-sky-700",
    basePrice: 40000,
  },
  {
    id: "Electricista",
    name: "Electricidad residencial e industrial",
    shortName: "Electricidad",
    description: "Instalaciones, fallas electricas y tableros.",
    icon: <Zap className="w-6 h-6" />,
    color: "text-amber-500",
    bg: "bg-amber-50 border-amber-200",
    chip: "bg-amber-100 text-amber-700",
    basePrice: 35000,
  },
  {
    id: "Fontanero",
    name: "Fontaneria y plomeria",
    shortName: "Plomeria",
    description: "Fugas, tuberias, sanitarios y puntos de agua.",
    icon: <Droplets className="w-6 h-6" />,
    color: "text-blue-500",
    bg: "bg-blue-50 border-blue-200",
    chip: "bg-blue-100 text-blue-700",
    basePrice: 35000,
  },
  {
    id: "Albanil",
    aliases: ["Albañil"],
    name: "Albanileria",
    shortName: "Albanileria",
    description: "Reparaciones locativas, muros y acabados.",
    icon: <Hammer className="w-6 h-6" />,
    color: "text-orange-500",
    bg: "bg-orange-50 border-orange-200",
    chip: "bg-orange-100 text-orange-700",
    basePrice: 30000,
  },
  {
    id: "Pintor",
    name: "Pintura",
    shortName: "Pintura",
    description: "Pintura interior, exterior y retoques.",
    icon: <Paintbrush className="w-6 h-6" />,
    color: "text-purple-500",
    bg: "bg-purple-50 border-purple-200",
    chip: "bg-purple-100 text-purple-700",
    basePrice: 30000,
  },
  {
    id: "General",
    name: "Mantenimiento general",
    shortName: "General",
    description: "Trabajos varios del hogar o negocio.",
    icon: <Wrench className="w-6 h-6" />,
    color: "text-slate-600",
    bg: "bg-slate-50 border-slate-200",
    chip: "bg-slate-100 text-slate-700",
    basePrice: 20000,
  },
];

export function getServiceCategory(categoryId) {
  return SERVICE_CATEGORIES.find(
    (category) => category.id === categoryId || category.aliases?.includes(categoryId)
  );
}
